/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AuthCadastroRouteImport } from './routes/_auth/cadastro'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedPagamentoRouteImport } from './routes/_authenticated/pagamento'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as NftsNftIdRouteImport } from './routes/nfts.$nftId'
import { Route as AuthenticatedPedidosOrderIdRouteImport } from './routes/_authenticated/pedidos.$orderId'
import { Route as AuthenticatedPerfilIndexRouteImport } from './routes/_authenticated/perfil.index'
import { Route as AuthenticatedPerfilAtividadeRouteImport } from './routes/_authenticated/perfil.atividade'
import { Route as AuthenticatedPerfilCarteirasRouteImport } from './routes/_authenticated/perfil.carteiras'
import { Route as AuthenticatedPerfilFavoritosRouteImport } from './routes/_authenticated/perfil.favoritos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPagamentoRoute = AuthenticatedPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPedidosOrderIdRoute =
  AuthenticatedPedidosOrderIdRouteImport.update({
    id: '/pedidos/$orderId',
    path: '/pedidos/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPerfilIndexRoute =
  AuthenticatedPerfilIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilAtividadeRoute =
  AuthenticatedPerfilAtividadeRouteImport.update({
    id: '/atividade',
    path: '/atividade',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilCarteirasRoute =
  AuthenticatedPerfilCarteirasRouteImport.update({
    id: '/carteiras',
    path: '/carteiras',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilFavoritosRoute =
  AuthenticatedPerfilFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/cadastro': typeof AuthCadastroRoute
  '/login': typeof AuthLoginRoute
  '/pagamento': typeof AuthenticatedPagamentoRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/perfil/atividade': typeof AuthenticatedPerfilAtividadeRoute
  '/perfil/carteiras': typeof AuthenticatedPerfilCarteirasRoute
  '/perfil/favoritos': typeof AuthenticatedPerfilFavoritosRoute
  '/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/cadastro': typeof AuthCadastroRoute
  '/login': typeof AuthLoginRoute
  '/pagamento': typeof AuthenticatedPagamentoRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/perfil/atividade': typeof AuthenticatedPerfilAtividadeRoute
  '/perfil/carteiras': typeof AuthenticatedPerfilCarteirasRoute
  '/perfil/favoritos': typeof AuthenticatedPerfilFavoritosRoute
  '/perfil': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/_auth/cadastro': typeof AuthCadastroRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/pagamento': typeof AuthenticatedPagamentoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/_authenticated/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/_authenticated/perfil/atividade': typeof AuthenticatedPerfilAtividadeRoute
  '/_authenticated/perfil/carteiras': typeof AuthenticatedPerfilCarteirasRoute
  '/_authenticated/perfil/favoritos': typeof AuthenticatedPerfilFavoritosRoute
  '/_authenticated/perfil/': typeof AuthenticatedPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/cadastro'
    | '/login'
    | '/pagamento'
    | '/perfil'
    | '/nfts/$nftId'
    | '/pedidos/$orderId'
    | '/perfil/atividade'
    | '/perfil/carteiras'
    | '/perfil/favoritos'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/cadastro'
    | '/login'
    | '/pagamento'
    | '/nfts/$nftId'
    | '/pedidos/$orderId'
    | '/perfil/atividade'
    | '/perfil/carteiras'
    | '/perfil/favoritos'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/carrinho'
    | '/_auth/cadastro'
    | '/_auth/login'
    | '/_authenticated/pagamento'
    | '/_authenticated/perfil'
    | '/nfts/$nftId'
    | '/_authenticated/pedidos/$orderId'
    | '/_authenticated/perfil/atividade'
    | '/_authenticated/perfil/carteiras'
    | '/_authenticated/perfil/favoritos'
    | '/_authenticated/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/cadastro': {
      id: '/_auth/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/pagamento': {
      id: '/_authenticated/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof AuthenticatedPagamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedidos/$orderId': {
      id: '/_authenticated/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthenticatedPedidosOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil/': {
      id: '/_authenticated/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AuthenticatedPerfilIndexRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/atividade': {
      id: '/_authenticated/perfil/atividade'
      path: '/atividade'
      fullPath: '/perfil/atividade'
      preLoaderRoute: typeof AuthenticatedPerfilAtividadeRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/carteiras': {
      id: '/_authenticated/perfil/carteiras'
      path: '/carteiras'
      fullPath: '/perfil/carteiras'
      preLoaderRoute: typeof AuthenticatedPerfilCarteirasRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/favoritos': {
      id: '/_authenticated/perfil/favoritos'
      path: '/favoritos'
      fullPath: '/perfil/favoritos'
      preLoaderRoute: typeof AuthenticatedPerfilFavoritosRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCadastroRoute: AuthCadastroRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilAtividadeRoute: typeof AuthenticatedPerfilAtividadeRoute
  AuthenticatedPerfilCarteirasRoute: typeof AuthenticatedPerfilCarteirasRoute
  AuthenticatedPerfilFavoritosRoute: typeof AuthenticatedPerfilFavoritosRoute
  AuthenticatedPerfilIndexRoute: typeof AuthenticatedPerfilIndexRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilAtividadeRoute: AuthenticatedPerfilAtividadeRoute,
  AuthenticatedPerfilCarteirasRoute: AuthenticatedPerfilCarteirasRoute,
  AuthenticatedPerfilFavoritosRoute: AuthenticatedPerfilFavoritosRoute,
  AuthenticatedPerfilIndexRoute: AuthenticatedPerfilIndexRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPagamentoRoute: typeof AuthenticatedPagamentoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
  AuthenticatedPedidosOrderIdRoute: typeof AuthenticatedPedidosOrderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPagamentoRoute: AuthenticatedPagamentoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
  AuthenticatedPedidosOrderIdRoute: AuthenticatedPedidosOrderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  NftsNftIdRoute: NftsNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
