/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NftsNftIdRouteImport } from './routes/nfts.$nftId'
import { Route as PedidosOrderIdRouteImport } from './routes/pedidos.$orderId'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PerfilCarteirasRouteImport } from './routes/perfil.carteiras'
import { Route as PerfilFavoritosRouteImport } from './routes/perfil.favoritos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosOrderIdRoute = PedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilCarteirasRoute = PerfilCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilFavoritosRoute = PerfilFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => PerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/perfil/carteiras': typeof PerfilCarteirasRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/perfil/carteiras': typeof PerfilCarteirasRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil': typeof PerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/perfil/carteiras': typeof PerfilCarteirasRoute
  '/perfil/favoritos': typeof PerfilFavoritosRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/pagamento'
    | '/perfil'
    | '/nfts/$nftId'
    | '/pedidos/$orderId'
    | '/perfil/carteiras'
    | '/perfil/favoritos'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/pagamento'
    | '/nfts/$nftId'
    | '/pedidos/$orderId'
    | '/perfil/carteiras'
    | '/perfil/favoritos'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/pagamento'
    | '/perfil'
    | '/nfts/$nftId'
    | '/pedidos/$orderId'
    | '/perfil/carteiras'
    | '/perfil/favoritos'
    | '/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  LoginRoute: typeof LoginRoute
  PagamentoRoute: typeof PagamentoRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  NftsNftIdRoute: typeof NftsNftIdRoute
  PedidosOrderIdRoute: typeof PedidosOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$orderId': {
      id: '/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof PedidosOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/carteiras': {
      id: '/perfil/carteiras'
      path: '/carteiras'
      fullPath: '/perfil/carteiras'
      preLoaderRoute: typeof PerfilCarteirasRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/favoritos': {
      id: '/perfil/favoritos'
      path: '/favoritos'
      fullPath: '/perfil/favoritos'
      preLoaderRoute: typeof PerfilFavoritosRouteImport
      parentRoute: typeof PerfilRoute
    }
  }
}

interface PerfilRouteChildren {
  PerfilCarteirasRoute: typeof PerfilCarteirasRoute
  PerfilFavoritosRoute: typeof PerfilFavoritosRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilCarteirasRoute: PerfilCarteirasRoute,
  PerfilFavoritosRoute: PerfilFavoritosRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  LoginRoute: LoginRoute,
  PagamentoRoute: PagamentoRoute,
  PerfilRoute: PerfilRouteWithChildren,
  NftsNftIdRoute: NftsNftIdRoute,
  PedidosOrderIdRoute: PedidosOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
